services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    networks:
      - orianderson
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: auth-service-pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: engc.anderson@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '8080:80'
    networks:
      - orianderson
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  orianderson:
    driver: bridge

volumes:
  postgres-data:
    driver: local
