# Utiliza a imagem oficial do Redis
FROM redis:latest

# Define o diretório de trabalho
WORKDIR /data

# Expõe a porta padrão do Redis
EXPOSE 6379

# Define o comando padrão para iniciar o Redis
CMD ["redis-server"]